### PR TITLE
Include corr (if available) and trans in 'Not Found' errors

### PR DESCRIPTION
**Pull request by gtorodelvalle**
- No linting issues
- 100% tests passed

### CODE REVIEW

**Comment by gtorodelvalle** [comment]
The implemented behaviour is the next one:

1. If no Fiware-Correlator is included in the received request, the STH will log:
```
time=2016-04-21T10:04:39.703Z | lvl=WARN | corr=n/a | trans=3b751c3e-1387-4479-820f-65acb9819ee8 | op=OPER_STH_GET | srv=testService | subsrv=/testServicePath | msg=GET //STH/v1/contextEntities/type/entityType/id/entityId/attributes/numericAttr01?lastN=1&dateFrom=2015-01-28T00:00:00&dateTo=2016-12-31T23:59:00, event={"request":"1461233079689:mac507514.hi.inet:12620:ina4fldx:10000","timestamp":1461233079702,"tags":["handler","error"],"data":{"msec":2.359002999961376,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}},"internal":true}
```
2. If the Fiware-Correlator header is included in the received request, the STH will log:
```
time=2016-04-21T10:05:49.387Z | lvl=WARN | corr=72fce1be-0956-4379-aa56-4fddb997339f | trans=05bc6507-6edb-4de3-a4fe-648253d3d9ce | op=OPER_STH_GET | srv=testService | subsrv=/testServicePath | msg=GET //STH/v1/contextEntities/type/entityType/id/entityId/attributes/numericAttr01?lastN=1&dateFrom=2015-01-28T00:00:00&dateTo=2016-12-31T23:59:00, event={"request":"1461233149381:mac507514.hi.inet:12620:ina4fldx:10001","timestamp":1461233149387,"tags":["handler","error"],"data":{"msec":0.2955029997974634,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}},"internal":true}
```

**Comment by XavierVal** [comment]
Let me clarify it a little bit with those 3 scenarios:

- If there is a header "Fiware-Correlator" in the request received -> STH has to response the same header received and log it.
 
- If there is NOT a header "Fiware-Correlator" in the request received -> STH has to copy the transaccionID value to the response as a new header "Fiware-Correlator" and log it too.

 - The only scenario where can appear the field like "corr=n/a" is just with internal operations like requests summary or other no requested actions by third party components.

**Comment by fgalan** [comment]
As far as I understand, the *general* behaviour is as follows:

* If there is a header "Fiware-Correlator" in the request received -> STH has to response the same header received and log it.

* If there is NOT a header "Fiware-Correlator" in the request received -> STH has to generate one

Under my understanding, "to copy the transaccionID" is a perfect way of generating the correlation ID, so everthign is ok.

**Comment by gtorodelvalle** [comment]
Yeah, that's the general behaviour.
My doubt was regarding the logging for the case when no `Fiware-Correlator` has been included in the request. In this case, should the `corr` value associated to the logged messages associated to the received request be set to the same value of the `trans` value generated in the STH component (this is, `corr=1234567890 | trans=1234567890`) or should it be left as 'n/a' (this is, `corr=n/a | trans=1234567890`) to easily identify the scenario where no `Fiware-Correlator` was sent?
In the response to the request, the `trans` value will be sent back as the Fiware-Correlator to the requester since none was provided in the request.
If I am not making myself clear, we can talk about it offline tomorrow.

**Comment by XavierVal** [comment]
That makes sense, let's go 👍

**Comment by fgalan** [comment]
> My doubt was regarding the logging for the case when no Fiware-Correlator has been included in the request. In this case, should the corr value associated to the logged messages associated to the received request be set to the same value of the trans value generated in the STH component (this is, corr=1234567890 | trans=1234567890) or should it be left as 'n/a' (this is, corr=n/a | trans=1234567890) to easily identify the scenario where no Fiware-Correlator was sent?
In the response to the request, the trans value will be sent back as the Fiware-Correlator to the requester since none was provided in the request.

Not sure how other IoTP components are doing it, but in the case of CB I'd say that the just-generated coordID (no matter if "copying" transactionID or other mechanism) is used in the logs. I think it make sense to doing in that way, e.g. to correlate logs in client associated to the response with the logs in the server associated to the request.

**Comment by XavierVal** [comment]
LGTM

**Pull request merged**
