### PR TITLE
FIX add node v14 to GitActions utests and remove node v10

### PR DESCRIPTION
**Pull request by fgalan**
Some previous things need to be done before merging:

- [x] Release a new version
- [x] Step Dockerfile to a node version >10
- [x] Analyze the problems in Node v16 test execution - the problem could be related with mongodb driver. By the moment we comment the entry and leave a FIXME comment

### CODE REVIEW

**Comment by fgalan** [comment]
From https://www.mongodb.com/docs/drivers/node/current/compatibility/#language-compatibility

imagen

But currently we have in packages.json:

```
"mongodb": "~3.6.12",
```

Maybe this could be the cause of the problem.

**Comment by fgalan** [comment]
Upgrade guide to 4.x:

https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_4.0.0.md

**Comment by AlvaroVega** [comment]
Perseo-fe is using node 16 and 16 in CI with the same version of mongo driver, 3.6.12

**Comment by AlvaroVega** [comment]
Maybe we can merge just adding node 14

**Comment by fgalan** [comment]
> Perseo-fe is using node 16 and 16 in CI with the same version of mongo driver, 3.6.12

Maybe Perse-fe works because is not using the same features set. Maybe STH is using a feature that makes the driver to fail.

**Pull request merged**
