### PR TITLE
Include FIWARE badges in the repo main page

### PR DESCRIPTION
**Pull request by gtorodelvalle**
- Fixes https://github.com/telefonicaid/fiware-sth-comet/issues/356

### CODE REVIEW

**Comment by gtorodelvalle** [comment]
@jmcantera, notice that for the time being a couple of badges do not show as they are supposed to:
1. The documentation badged will show as expected once the component ReadTheDocs documentation lands in master (at the end of this sprint).
2. The Docker badge will show as expected once the automatic build is created in the FIWARE Docker Hub available at https://hub.docker.com/r/fiware/

**Comment by jmcanterafonseca** [comment]
no, we are specifying what badges are mandatory but you can have as much as badges in your repo, provided the ones that appear first from left to right are the mandatory ones

**Comment by gtorodelvalle** [comment]
Great! ;) Thanks

**Comment by gtorodelvalle** [comment]
@jmcanterafonseca gave me his LGTM offline. Could you please check it and land it, please, @XavierVal ? :) Thanks!

**Pull request merged**
