### PR TITLE
Fix for issue #559

### PR DESCRIPTION
**Pull request by SwatiNEC**
This patch will fix the issue #559  of connection lost in case of mongodb restarted in case of GET history data API and notify API of sth-comet.

### CODE REVIEW

**Comment by SwatiNEC** [comment]
Hi @mapedraza 

I have analyzed the code base of perseo. In perseo, when we call an API they are making database connection every time and if database is down then it will try to reconnect multiple times as they are using **reconnectTries**.
For implementing database connection like perseo, we need to upgrade mongodb and we also need to change db connection code and make a connection for every API.

Please share your opinion.

**Comment by mapedraza** [comment]
Hi @SwatiNEC , 

Reviewing the code, the function `getDbAux()` is only used in 2 functions on the same file (lib/db.js)

- [`function getDb(callback)`](https://github.com/telefonicaid/perseo-fe/blob/master/lib/db.js#L87-L92)
- [`function getOrionDb(callback) `](https://github.com/telefonicaid/perseo-fe/blob/master/lib/db.js#L93-L98)

The first one, which is the one we are interested in, is only called at the beginning of the execution [here](https://github.com/telefonicaid/perseo-fe/blob/c2b90521cb7c526f4429c8d3d9fdc6483eab20fc/lib/perseo.js#L125) as part of the initial `async.series()`

For having the same approach in SHT, the steps to complete are the followings:

- Update the MongoDB driver to same version (3.6.8)
- Update how STH configures the driver at the beginning of the execution (adding `reconnectTries` and   `reconnectInterval` parameters)

For reviewing and testing purposes we can split the tasks in 2 different PRs, creating a new one for updating the driver.

Once again, thank you so much for your willingness to contribute to this component. Let me know what you thing and do not hesitate to ask if you have any question or doubt.

**Comment by fgalan** [comment]
@SwatiNEC bottom line in @mapedraza is that in perseo-fe we don't have a connection every time Perseo processes an API request. On the contrary, MongoDB connection is created at the startup of the program, then reused every time it's needed.

In addition, divide the task in two steps (first one upgrating diver, second one use it in a way similar to Perseo to implement reconnects) as @mapedraza proposes is a good idea.

**Comment by SwatiNEC** [comment]
Hi @mapedraza 

> * Update the MongoDB driver to same version (3.6.8)

For the above mentioned point you earlier shared a reference for the PR [#548](https://github.com/telefonicaid/fiware-sth-comet/pull/548). I need to get the completion timeline for the same because as per my understanding I can only resume once that PR is completed.
Also, required your suggestion for any workaround so that I can resume the activity.

**Comment by mapedraza** [comment]
Hi @SwatiNEC 

My suggestions is you could take PR #548 as starting point (I mean, reproducing the same little change in packages.json in your own branch), then, you can complete the needed changes in the code to use the new version of the driver. You can have a look to the equivalent PR on Perseo-fe: https://github.com/telefonicaid/perseo-fe/pull/481  in the case in can be useful.

**Comment by fgalan** [comment]
I understand this PR has been overpassed by PR https://github.com/telefonicaid/fiware-sth-comet/pull/574 and should be closed

**Comment by fgalan** [comment]
> I understand this PR has been overpassed by PR #574 and should be closed

@SwatiNEC @Gauravp-NEC what do you think?

**Comment by Gauravp-NEC** [comment]
> > I understand this PR has been overpassed by PR #574 and should be closed
> 
> @SwatiNEC @Gauravp-NEC what do you think?

@fgalan, Yes this PR is overpassed by PR https://github.com/telefonicaid/fiware-sth-comet/pull/574. This PR can be closed now.

**Comment by fgalan** [comment]
> @fgalan, Yes this PR is overpassed by PR #574. This PR can be closed now.

Thanks for confirming it. Closing.

**Pull request closed without merging**
